### ISSUE TITLE
Script usage and secrecy 

### ISSUE THREAD

**Issue by weilies** [grahamearley/FirestoreGoogleAppsScript#106]
I finally make the code works and able to import data into from sheet to my firebase demo environment.
But here my concern, is it production ready? I have concern if i have to expose my "privateKey", "projectId" from my service account, does it means i will expose my client's data if i run it with REAL data?

I would like to understand my concern well before putting into production environment and avoid a trust-break with my clients.

Thanks for the clarification.

**Comment by LaughDonor** [comment]
I'd like to think it is. There's no glaring bugs, and I'm able to fix any in a reasonable amount of time; though I don't have time for new features at the moment.

As far as "exposing" your data:

1. You can read the code yourself; this application does not track any of that information, and
1. The sensitive data can be stored within Google's [Property Service](https://developers.google.com/apps-script/guides/properties) so that it isn't shown in plaintext within your code. That's how all of my applications (and test projects) use this library keep my data secure. There's a short example on this project's [README](//github.com/grahamearley/FirestoreGoogleAppsScript#configuration-template) (in depth instructions can be done with the previous link).

I hope this helps.
