### ISSUE TITLE
Firestore rules missing for bearer tokens

### ISSUE THREAD

**Issue by supertopoz** [grahamearley/FirestoreGoogleAppsScript#12]
Hi there. 

I have tried this library this is the result I get: 

{
    "error": {
        "code": 403,
        "message": "Missing or insufficient permissions.",
        "status": "PERMISSION_DENIED"
    }
}

I have picked apart the code and found the a bearer token is generated as expected. 

Might I ask if we up date the docs with example rules for the Firestore DB that except a bearer token for Authentication. I have tried many different rule sets but none of them seem to match with this approach to authentication.

**Comment by grahamearley** [comment]
My first thought here is that maybe your service account doesn't have the correct permissions. From my readme:

>Follow [these instructions](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatinganaccount) (just the "Creating a service account" section) to obtain a service account email address and private key. Ensure you have given the account full read/write access to the Datastore scope. You can do this in the "Create a service account" window by selecting "Datastore" in the "Role" dropdown and choosing "Cloud Datastore Owner."

This is how I use the library — giving the scripts full permissions to access the database. With this setup, your script can still access the database even if you set the rules to not allow reads and writes (because the scripts have admin access).

Can you try re-creating your service account (and putting the new key and email into your script) and making sure you have given it full access to the Datastore scope?

**Comment by supertopoz** [comment]
Arh... I feel such a fool. I was using the credentials from the Apps script not from Firebase. FYI I made a pull request with a Readme update so others don't make the same mistake as me. I hope you don't mind.

**Comment by grahamearley** [comment]
@supertopoz Glad you got it working! 

Yeah, a readme update would be good. I don't see your pull request though, could you resubmit it?
