### ISSUE TITLE
Prevent auto conversion to GeoPoint

### ISSUE THREAD

**Issue by Stev3nsen** [grahamearley/FirestoreGoogleAppsScript#156]
Hey guys, thanks for your awesome work. I have simple question. See below.

## Minimal Code to Reproduce the Problem
```javascript
const firestore = FirestoreApp.getFirestore(email, key, projectId);

function myFunction() {
  const document = {
    location: {
      "latitude": 10.1,
      "longitude": 10.1
    }
  }

  firestore.createDocument("Test", document)
}
```

## Explain the Problem in Detail

When i create a document that contains a map with following structure
```javascript
  const document = {
    "someName": {
      "latitude": 10.1,
      "longitude": 10.1
    }
  }
```
a document field gets some kind of auto converted to a geopoint type.

### Expected result
![image](https://user-images.githubusercontent.com/6922937/217881892-bf8ee846-207c-40e4-9657-8975e1d1b8ae.png)

In Firestore console i expected my location field as map structure and not as geopoint.

### Actual result
![image](https://user-images.githubusercontent.com/6922937/217882331-0894a750-0df2-49c2-90ec-648c4b6cda7e.png)

The location field is automatically converted in a geopoint. Is there a way to prevent this behavior?

**Comment by LaughDonor** [comment]
It is automatic.. it works off of [Duck Typing](https://en.wikipedia.org/wiki/Duck_typing) ([source](https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/main/Document.ts#L149-L152)). If you don't want to do that, you'll have to rename the keys, or add an additional property since it's typically beneficial to use the [built-in storage type](https://cloud.google.com/firestore/docs/reference/rest/Shared.Types/LatLng) that Firestore provides.
