### ISSUE TITLE
Allow updateMask to be set for Patch/Updating documents

### ISSUE THREAD

**Issue by LaughDonor** [grahamearley/FirestoreGoogleAppsScript#23]
Currently `updateDocument` behaves exactly like `createDocument`, and will always overwrite the document if it exists, and create a new one if it doesn't.

Adding this functionality will allow users to update certain fields and ignore others. A true "patch".

Details can be found in the docs: https://cloud.google.com/firestore/docs/reference/rest/v1beta1/projects.databases.documents/patch#query-parameters

**Comment by vaheg** [comment]
Any updates on this?
This practically makes it useless, since this is like main feature of the firestore

**Comment by meiDeveloper** [comment]
Add the following 4 lines before the `return`  line in `updateDocument_` in Write.js:

```js
var fieldPaths = Object.keys(fields)
while (fieldPaths.length){
  request.addParam('updateMask.fieldPaths', fieldPaths.pop())
}
```

It took a while to figure out, but updateMask needs to be constructed with dot notation in the query string, one field at a time:
`?updateMask.fieldPaths=active&updateMask.fieldPaths=name`

**Comment by grahamearley** [comment]
Sorry for the delay on responding to this! Here's what I'm thinking — @webstermath's PR #39 looks like it does the trick. However, I have one design question that I'd like some input on.

With the changes in #39, only the fields sent in the update request will be updated; any other fields in the document on the server will stay the same. However, if you send an empty object `{}` with no fields, then all the fields in the document on the server will be deleted.

Would this behavior be expected? Or would you expect the update function to do nothing since you sent no fields to be updated?

**Comment by grahamearley** [comment]
Here's an idea on how to handle this case:

Add a boolean parameter `mask` to the function. If `mask` is false, then the update function will work in the same way as it did before this change — i.e. it will replace the document with the new object passed in. If `mask` is true, then the object passed in will be used as a mask, only updating the fields that are contained in it.

So, if `mask` is true, then passing in `{}` will result in nothing changing. If `mask` is false, then passing in `{}` will update the document to be empty.

This change would allow the update function to continue behaving as it has before, but it would also allow the function to be used for masking.

@webstermath — I'm going to assign this issue to you since you've got a PR in the works. Could you make these changes in your PR? Let me know if you have any questions on my suggested approach!

**Comment by webstermath** [comment]
@grahamearley, you are suggesting that the update function should generally have the update mask turned off by default and not just in the special case of an empty object?

**Comment by grahamearley** [comment]
Hm. Yeah, that's what I was suggesting, but I'm not too firm either way. 

I personally use `update` to replace entire documents with new contents, and wouldn't want to surprise people with this change if they weren't expecting it to all of the sudden update with a mask. I know that not everyone uses it this way, so we could go the route of having mask on by default.

My biggest goal here is to retain the option to use `update` for replacing entire documents and not just doing a mask.

Do you feel like it makes more sense for mask to be on by default?

**Comment by webstermath** [comment]
So I see pros and cons both ways, but for the sake of backwards compatibility, I went with your original suggestions.

**Comment by grahamearley** [comment]
Available in [v22](https://github.com/grahamearley/FirestoreGoogleAppsScript/releases/tag/v22)! 🎈
