### ISSUE TITLE
key parsing

### ISSUE THREAD

**Issue by JohanKlos** [grahamearley/FirestoreGoogleAppsScript#34]
When the key is entered from - say - a googlesheet, it is then not parsed correctly, as it still contains the \n in the string.
Maybe the library could automatically parse it so, for instance:

- any \n are replaced correctly
- anything before and after the key ("-----BEGIN PRIVATE KEY" and "END PRIVATE KEY-----\n" is automatically discarded

**Comment by grahamearley** [comment]
Are you saying you want the `-----BEGIN PRIVATE KEY` and `END PRIVATE KEY-----\n` pieces to be removed from the key? I include those and the `\n`s in my key when using the library and it works for me.

Are you able to get the library to work with a key including these characters?

**Comment by JohanKlos** [comment]
No, I'm saying remove everything from before and after those pieces.... and - if missing - add them.

**Comment by JohanKlos** [comment]
I've only been able to get the library working by using a different method of entering the key (not as a getvalue() from the sheet, but rather as a string inside the scripteditor).

**Comment by grahamearley** [comment]
Ah okay, I see what you're saying.

I think this is out of the scope of this library. The purpose of the library is to interface with Firestore. Any issues with getting your key out of a Google Sheet should be dealt with in your own code IMO. This will also prevent our library from having issues if Google changes the format of the key at some point.

**Comment by LucasAschenbach** [comment]
I think the problem is that when loading the string, each `\n` character from the key is not seen as symbolic character sequence for a line-break but instead as a literal character sequence `\` + `n`. To fix this, try applying `.replace(/\\n/g, '\n')` to your imported private key string.

I also created a pull-request #112 to add this to the README.

**Comment by LaughDonor** [comment]
Thank you for your PR @LucasAschenbach , I haven't seen anyone else experience this issue.

When you put in your key, are the new lines literal, or encoded?

The example and documentation are meant to be taken literally.

**Comment by LucasAschenbach** [comment]
The key argument exception is thrown either way. The issue seems to be with the Google Apps Script application, as discussed here: https://github.com/googleworkspace/apps-script-oauth2/issues/122. Apparently, the string returned by `getProperty('private_key')` is encoded with the separate unicodes for `\` and `n` and not the new-line unicode for `\n` as expected.

You can easily reproduce the exception by adding your private key under **File > Project Properties > Script Properties** and running:
```javascript
const props = PropertiesService.getUserProperties(); // Or .getScriptProperties() if stored in Script Properties
const [email, key, projectId] = [props.getProperty('client_email'), props.getProperty('private_key'), props.getProperty('project_id')];
const firestore = FirestoreApp.getFirestore(email, key, projectId);
```
---
Now, if you want the documentation to assume that the private key is stored using literal line-breaks (i.e. without `\n` chars), my proposed solution won't work. However, using literal line-breaks is a lot less elegant as it requires more work on the developers end. For some reason, the Google Apps Script application seems to be converting all literal line-breaks into spaces when pasting a string into the value field. This means, the replace operation would, in addition to replacing the space character, also have to distinguish between intentional spaces and spaces added as replacement for line-breaks.

I think, until the Google Workspace Team fixes this issue, this is the best solution.
