### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by iaarab** [grahamearley/FirestoreGoogleAppsScript#36]
Is the onSnapshot implemented for realtime updates?

**Comment by grahamearley** [comment]
It's not, currently. I hadn't thought about implementing it because I think of the library as something usually to be used with Google Sheets, where those sort of async / background threading use cases don't really apply (most operations are just direct reads and writes).

We could definitely look into it, though! Out of curiosity, what's the use case you have in mind for this?

**Comment by LaughDonor** [comment]
We won't be able to implement it as it currently isn't supported in the [REST API](https://firebase.google.com/docs/firestore/reference/rest/). 

The only workarounds I can think of are to poll the document and check for changes, or to implement a middleman service that will send a [post request](https://developers.google.com/apps-script/guides/triggers/#doget_and_dopost) to your script when the document changes.

**Comment by grahamearley** [comment]
Thanks for the knowledge @LaughDonor! Still curious about the use case @iaarab, but I'll close this issue for now since we can't do it.

**Comment by iaarab** [comment]
I'm using this library with google appmaker [https://developers.google.com/appmaker/](url).
And the server code in appmaker is AppScript

**Comment by grahamearley** [comment]
Yeah, that's a bummer. Would be cool to use it with Google Appmaker. We can re-open this in the future if anything changes that makes this more doable!
