### ISSUE TITLE
Add method for getting list of documents (as objects) from a collection

### ISSUE THREAD

**Issue by grahamearley** [grahamearley/FirestoreGoogleAppsScript#5]
Currently, if you want to get a list of all documents (as JSON objects) from a collection, you have to 
1. Call `getDocumentIds(pathToCollection, email, key, projectId)` to get the IDs for the collection
2. Loop through these IDs and combine the `pathToCollection` with the ID to make the document path.
3. Call `getDocumentFields(path, email, key, projectId)` for each document ID / path to get a JSON object for that document.

This should be combined into a single method.

**Comment by thesandlord** [comment]
Hey @grahamearley, we recently did a Hackathon and added query support to this library. I'll hopefully send a PR with this functionality soon, and it will allow you to get multiple documents from a collection easily. This has the big advantage of doing a single URLFetch instead of O(n) URLFetches.

Right now, I'm thinking the method call will look very much like the "get" method, but will have a param called "query" instead of "path" that will be a [Firestore StructuredQuery](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/StructuredQuery).

I'm thinking it will look something like this:

```javascript
query(query, email, key, projectId) {
  query_(path, query, email, key, projectId);
}

getAllDocuments(path, email, key, projectId) {
  var query = {
    from: [{collectionId: path}]
  };
  query_(query, email, key, projectId);
}

query_(query, email, key, projectId) {
  // Code to Query and Return Documents
}

```

**Comment by grahamearley** [comment]
Awesome! The lack of query support is definitely a big hole in this library — and this is gonna provide a much better solution to getting a list of documents than the one I proposed!

Looking forward to the PR.

**Comment by thesandlord** [comment]
#6

**Comment by grahamearley** [comment]
Currently this is also done in #10 in a less-ideal way. I'll keep this issue open, though, because using the query method in #6 would be great, once we get that PR merged.

**Comment by grahamearley** [comment]
Covered by #28 and released in [v16](https://github.com/grahamearley/FirestoreGoogleAppsScript/releases/tag/v16)!
