### ISSUE TITLE
Feature Request: startAt(), startAfter(), endAt() etc. methods for queries

### ISSUE THREAD

**Issue by rohan039** [grahamearley/FirestoreGoogleAppsScript#77]
The inclusion of these methods would be a lifesaver if possible:

https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#start-at
https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#start-after
https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#end-at

**Comment by LaughDonor** [comment]
This functionality already existed by combining the `.offset` and `.limit` query functions. 

However, I created a PR so that you can use the `.range(start, end)` query function to to combine the two if needed. As far as the "startAfter" and "endBefore", they are the same, just off by one. You should be able to make your adjustments in the code before using these functions.
