### ISSUE TITLE
Appending values to an array field?

### ISSUE THREAD

**Issue by kaelansmith** [grahamearley/FirestoreGoogleAppsScript#78]
Is it currently possible to append values to an array field using this library's updateDocument() method (i.e. add values to an array without replacing existing ones)? I know that Firestore supports this with [arrayUnion() ](https://firebase.google.com/docs/firestore/manage-data/add-data). If not, do you plan on implementing this feature any time soon?

**Comment by LaughDonor** [comment]
In short, not yet.

The linked function you have listed operates off the JavaScript API which (internally) communicates with the Database using the [RPC API](https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.v1beta1). **This** library (internally) communicates with the Database using the [REST API](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases.documents). And since this feature isn't available in the REST API *yet*, we're unable to add this feature for this library the way it is written now.
