### ISSUE TITLE
document.obj is returning null

### ISSUE THREAD

**Issue by Subroid** [grahamearley/FirestoreGoogleAppsScript#98]
## Minimal Code to Reproduce the Problem
```javascript
const firestore = getFirestore();
  const allDocumentsWithMetadata = firestore.getDocuments(myCollection);
 
  allDocumentsWithMetadata.forEach(function(documentWithMetaData) {
    document = documentWithMetaData.obj
    Logger.log(document.fields);
  });

```

## Explain the Problem in Detail

After applying forEach method to documents[] returning by firestore.getDocuments(myCollection) and converting each document metadata item to document.obj and trying to access fields giving null.
![image](https://user-images.githubusercontent.com/29721105/86629301-d845ea80-bfe8-11ea-88a2-0b7ad2a9c508.png)
![image](https://user-images.githubusercontent.com/29721105/86629430-0b887980-bfe9-11ea-8876-5a33de5290b7.png)

##### Library Version: 32

**Comment by LaughDonor** [comment]
Your data doesn't have the `fields` property, that's why you getting `null` values returned.

Updating your logger to use `Logger.log(document)`, you should see your original data.

**Comment by Subroid** [comment]
Here's the original data...

![image](https://user-images.githubusercontent.com/29721105/86690857-ecf4a380-c025-11ea-97f6-94fab7d56f41.png)

And minimal code to reproduce it...

![image](https://user-images.githubusercontent.com/29721105/86691028-17def780-c026-11ea-9a1f-6cacbbe373e9.png)

**Comment by LaughDonor** [comment]
This is by design. The `documentWithMetaData`, the "original data", that you are iterating over is ***an internal [`Document`](/grahamearley/FirestoreGoogleAppsScript/blob/main/Document.ts#L4) object***. This mirrors the same [Document](https://firebase.google.com/docs/firestore/reference/rest/v1/projects.databases.documents#Document) object from Firestore since it is the raw result from fetching your data.

To transform the response and get all of your raw data:
```javascript
const allDocumentsWithMetadata = firestore.getDocuments(myCollection);
const allDocuments = allDocumentsWithMetadata.map(function(documentWithMetaData) { return documentWithMetaData.obj; });
```

and `allDocuments` will be an array of all of your data. Just as I stated in [your previous issue #97](/grahamearley/FirestoreGoogleAppsScript/issues/97#issuecomment-651414275).
